### PR TITLE
Reorganize repo

### PR DESCRIPTION
**Pull request by iankronquist**
Review this one very carefully. It could break absolutely everything.
@kabilans @pixel5919, could you make sure that this doesn't break any of your stuff?

### CODE REVIEW

**Comment by pixel5919** [comment]
On my local repository, I did these commands:
`
git fetch origin 
git checkout -b reorganize-repo origin/reorganize-repo
git checkout reorganize-repo
git merge master
make
sudo COMPOSE_API_VERSION=1.18 ./beeswax`

./beeswax ran but I couldn't connect to my localhost:8000, modified Vagrantfile, 
`$ exit
$ vagrant halt
$ vagrant up --provision
$ vagrant ssh
`
and the website couldn't connect

**Comment by iankronquist** [comment]
Zach, some of those commands (particularly `git checkout -b`) look wrong. When you ran them did you see the organization of the files change? e.g. did the `src/` directory cease to exist?

**Comment by pixel5919** [comment]
Yes, /src disappeared, but it looks as if merging the other branches caused this branch to fall too far behind.

**Comment by iankronquist** [comment]
@pixel5919 I just fixed that. You may need to pull again/delete the branch and pull again.

**Comment by pixel5919** [comment]
I did this: 
```
git branch -D reorganize-repo
Git fetch --all
Git checkout reorganize-repo
Make clean
Make
```
Started the vagrant VM on master branch to verify setup, stopped containers, deleted containers and checked out reorganize-repo. 
```
$ docker-compose stop mysql wordpress
$ docker rm $(docker ps -a -q)
$ git checkout reorganize-repo
$  sudo COMPOSE_API_VERSION=1.18 ./beeswax 
```
Received this `Error establishing a database connection`

**Comment by kabilans** [comment]
I just pulled the latest version (not reorganize-repo) on my droplet, got
the same error.

**Comment by kabilans** [comment]
A little research shows that the issue is probably in the wp-config file. I
unfortunately don't have enough time tonight to fix this and I also need to
redo the video (the file format is corrupt).

On Mon, May 16, 2016 at 6:19 PM, Sibi Kabilan <ibisnopmes@gmail.com> wrote:

> I just pulled the latest version (not reorganize-repo) on my droplet, got
> the same error.
>



-- 

Sempon Sibi Kabilan

**Pull request merged**
